# 动态线程池配置
poolify:
  executors:
    - thread-pool-name: dtp1
      queue-timeout: 100
      run-timeout: 100
      core-pool-size: 200
      maximum-pool-size: 200
      keep-alive-time: 100
  notify-platforms:
    - platform: ding
      url: http://dingding.com
      token: abc
      receivers: ab,ac,bc

  management:
    enabled: true
    addr: http://localhost:8091
    collection-cron: "0/10 * * * * ?"
  registry:
    type: nacos
    nacos:
      host: localhost
      port: 8848
#      group-id:
  web:
    context-path: /api
spring:
  name: testApplicationName
#  datasource:
#    url: jdbc:mysql://localhost:3306/poolify?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
#    username: root
#    password: hcj
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      config:
#        server-addr: localhost:8848
#        import-check:
#          enabled: false


