server:
  port: 8091

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/poolify?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    username: root
    password: hcj
    driver-class-name: com.mysql.cj.jdbc.Driver