version: '3.9'
services:
  nacos:
    image: nacos/nacos-server:v2.3.1
    container_name: nacos-server
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
#      - NACOS_AUTH_ENABLE=true # 可选，是否开启认证功能
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./nacos/logs:/home/nacos/logs # 挂载日志文件
#      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties # 可选，挂载自定义配置文件
#    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
